# Configuration for Cloudflare Pages
[build]
command = "bun run cf-build-main"
base = "/"
output_directory = "apps/main/.next"
root_dir = "."

[build.environment]
NODE_VERSION = "18"
BUN_VERSION = "1.2.3"
