# Configuration for Cloudflare Pages - Tools Site
[build]
command = "bun run cf-build-tools"
base = "/"
output_directory = "apps/tools/.next"
root_dir = "."

[build.environment]
NODE_VERSION = "18"
BUN_VERSION = "1.2.3"