name = "tools-ryancruz-com"
compatibility_date = "2023-10-30"

[site]
bucket = "./dist"

[build]
command = "cd ../../ && bun turbo run build --filter=tools"

[env.production]
routes = [
  { pattern = "/*", zone_name = "tools.ryancruz.com" }
]